// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blockquote: dynamic(() => import("./Blockquote")),
  full_video: dynamic(() => import("./FullVideo")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
};
